// @flow strict
export const SLIDE_WIDTH = 720
export const SLIDE_HEIGHT = 450

// actions
export const LOAD_DECK = "LOAD_DECK"
export const LOAD_EMBEDDED_DECK = "LOAD_EMBEDDED_DECK"

export const CREATE_DECK = "CREATE_DECK"
export const UPDATE_DECK = "UPDATE_DECK"
export const DELETE_DECK = "DELETE_DECK"
export const LOAD_DECKS = "LOAD_DECKS"
export const LOAD_FEATURED_DECKS = "LOAD_FEATURED_DECKS"
export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGOUT = "USER_LOGOUT"

export const DECK_LOADED = "DECK_LOADED"
export const EMBEDDED_DECK_LOADED = "EMBEDDED_DECK_LOADED"
export const DECKS_LOADED = "DECKS_LOADED"
export const FEATURED_DECKS_LOADED = "FEATURED_DECKS_LOADED"
export const DECK_DELETED = "DECK_DELETED"
export const DECK_UPDATED = "DECK_UPDATED"
export const UPLOAD_ASSETS = "UPLOAD_ASSETS"
export const SEARCH_UNSPLASH = "SEARCH_UNSPLASH"
export const UNSPLASH_FETCHED = "UNSPLASH_FETCHED"
export const CREATE_FLASH_MESSAGE = "CREATE_FLASH_MESSAGE"

export const SET_PRESENTATION_SLIDE_IDX = "SET_PRESENTATION_SLIDE_IDX"
export const SET_FLASH_MESSAGE = "SET_FLASH_MESSAGE"
export const CLEAR_FLASH_MESSAGE = "CLEAR_FLASH_MESSAGE"
